### ISSUE TITLE
Create schema validation test for GeoRSS 1.0 and 1.1

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-georss10#2]
Attached are the schemas to use.

Create separate conformance classes for GeoRSS 1.0 and 1.1 in the ETS.

[georss_schemas.zip](https://github.com/opengeospatial/ets-georss10/files/5504602/georss_schemas.zip)

**Comment by keshavnangare** [comment]
@dstenger @ghobona 

I imported the XSD's into IDE and it is showing some errors in the following element.
1. File: georss-1_1/1.0/georss-2015.xsd
    `<xs:element ref="gml:Point"/>` (Line no. :12)
    Error: src-resolve: Cannot resolve the name 'gml:Point' to a(n) 'element declaration' component.
    
2. File: georss-1_1/1.0/gmlgeorss-2015.xsd
    `<complexType name="MetaDataPropertyType">` (Line no. :179)
    Error: cos-nonambig: "http://www.opengis.net/gml":_MetaData and WC[##any] (or elements from their substitution group) 
              violate "Unique Particle Attribution". During validation against this schema, ambiguity would be created for those two 
              particles.

Should I update the XSD's?

**Comment by keshavnangare** [comment]
Following changes to be done for fixing the above comment issues respectively:
1. The definition of the element is missing from the same file or locally referred schema location file. I checked the file name in the schema location attribute and found that no file exists with that name in same folder so either we can update the file name in the schema location attribute or rename the other file present in the same folder. (Please refer below table Sr no.1)
2. The sibling declarations of element ref ("gml:_MetaData") and `any` are ambiguous. To resolve the issue we can update `choice` to `sequence` tag or we can mention the namespace as `##other` for `any` tag. (Please refer below table Sr no.2)

|Sr No.|Line No.|File name|Current|Update|
|---|---|---|---|---|
|1|3|georss-1_1/1.0/georss-2015.xsd|schemaLocation=gmlgeorss.xsd|schemaLocation=gmlgeorss-2015.xsd|
|2|187|georss-1_1/1.0/gmlgeorss-2015.xsd|'<'choice minOccurs="0"'>'|'<'sequence minOccurs="0"'>'|

**Comment by keshavnangare** [comment]
I have renamed the XSD files because of the above comment issue(1). I have created two tests and tested them successfully on my machine. Please find the changes in #3 PR.

**Comment by dstenger** [comment]
@ghobona @keshav-nangare 

Unfortunately, the two test datasets provided by the specification fail the test suite (same as the examples in the provided zip file):
* http://docs.opengeospatial.org/cs/17-002r1/17-002r1.html#37
* http://docs.opengeospatial.org/cs/17-002r1/17-002r1.html#38

Messages:
* atom-boat-trip.xml
```
1 schema validation error(s) detected. Severity: ERROR Message: cvc-elt.1.a: Cannot find the declaration of element 'feed'. Location: 
```
* atom-calendar-of-events.xml
```
3 schema validation error(s) detected. Severity: ERROR Message: cvc-elt.1.a: Cannot find the declaration of element 'feed'. Location: Severity: ERROR Message: cvc-complex-type.2.3: Element 'gml:LinearRing' cannot have character <br>[children], because the type's content type is element-only. Location: Severity: ERROR Message: cvc-complex-type.2.4.b: The content of element 'gml:LinearRing' is not complete. One of '{"http://www.opengis.net/gml":posList}' is expected. Location: 
```

I checked the schemas and "feed", for example, seems not to be defined.
Thus, the schema defining elements in namespace "http://www.w3.org/2005/Atom" must also be included?
Also, it is strange that the gml related errors occur as those should be covered by the provided schemas.

**Comment by ghobona** [comment]
The schema of 'feed' is encoded in RelaxNG at https://github.com/opengeospatial/ets-georss10/blob/master/src/main/resources/org/opengis/cite/georss10/rnc/atom.rnc

**Comment by ghobona** [comment]
Some relevant information https://stackoverflow.com/questions/446700/is-there-any-defined-atom-syndication-xml-schema
