### ISSUE TITLE
Update Web Browser Interface

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-georss10#5]
Currently, the Web Browser Interface looks like this:

![Bildschirmfoto vom 2021-03-23 12-59-03](https://user-images.githubusercontent.com/2989166/112143034-a0fb8600-8bd7-11eb-909f-82df4c338f55.png)

Following must be updated:
* Text describing capabilities of test suite.
* Default location can be removed.
* Selection between Conformance Class Level 1 and 2 can be removed?

**Comment by dstenger** [comment]
@keshav-nangare
Can you please work on
* Default location can be removed.
* Selection between Conformance Class Level 1 and 2 can be removed?

**Comment by keshavnangare** [comment]
I have removed default location and class selection from input form. Please find the changes in #6 PR.
